### ISSUE TITLE
Error (void-function er/enable-minor-mode-expansions)

### ISSUE THREAD

**Issue by wandersoncferreira** [flatwhatson/expand-region-subword#1]
https://github.com/flatwhatson/expand-region-subword/blob/2f7037401a6d90fc12c822016fdc3f81257e6076/subword-mode-expansions.el#L45

There's something missing? I can find `(er/enable-mode-expansions)` but if I make this change, the subword expansion is not working as expected.

**Comment by flatwhatson** [comment]
Ah, I think your expand-region is too old. The `er/enable-minor-mode-expansions` was added quite recently.

**Comment by wandersoncferreira** [comment]
I am using `expand-region-0.11.0` as expected in the dependencies of the package :/ Which one should I have?

**Comment by flatwhatson** [comment]
OK, that is a fair point.  Unfortunately the situation is a little tangled and I'm still getting on top of it all.

Technically, `expand-region-0.11.0` already includes this functionality, but it is not enabled by default due to a bug in the auto-loading logic.  The next release of `expand-region` will not include this functionality at all, leading to the creation of this package.

I think the best approach will be for me to make this package compatible with `expand-region-0.11.0` as you have reasonably expected.  Please give me a minute :)

**Comment by flatwhatson** [comment]
@wandersoncferreira Please try with the latest version, and thanks for your help!

**Comment by wandersoncferreira** [comment]
thanks! Sorry for bothering more, but the behavior of the package for me right now is the following:

~ emacs-lisp-mode
`(setq |CamelCaseTest t)`

After `er/expand-region`:
`(setq Camel|CaseTest t)`

One more time:
`(setq CamelCaseTest| t)`

I would expect the following:
`(setq CamelCase|Test t)`

Can you confirm it?

**Comment by flatwhatson** [comment]
Yes, that's normal behavior of this package.  It selects the current subword, then the current word, then the current statement/defun/etc.  I believe that is just how expand-region works.
